from .Plotter import SavePlotAsVectors
from .Linear1 import Linear1
from .CNN1 import CNN1
from .CNN2 import CNN2
from .CNN3 import CNN3
from .CNN4 import CNN4
from .CNN5 import CNN5
from .CNN6 import CNN6
from .SVM1 import SVM1
from .SVM2 import SVM2
from .SVM3 import SVM3